name: FairyTailCraft
main: bluenova.fairytailcraft.FairyTailCraft
version: 0.1
commands:
  fairytailcraft:
   description: Fairy Tail Mage Plugin Commands
   usage: /<command>
   aliases: [ftc, ft, fairytail]